### PR TITLE
add a dict file for libfuzzer

### PR DESCRIPTION
**Pull request by lenawanel**
I've used this with `libafl_libfuzzer` on grimoire for finding bugs, it's more effective than just pure libfuzzer, but I imagine sth similar to tokenafl would be even more effective.

Implementing arbitrary for the hir, and making it printable to capy would also be a effective way to fuzz the parser for correctness.

### CODE REVIEW

**Comment by NotAFlyingGoose** [comment]
I'm not super familiar with a dictionary for the fuzzer, could you explain how it works?

**Comment by lenawanel** [comment]
it's a file that gives the fuzzer tokens it can insert (and potentially do some other mutations with) 
[here is the libfuzzer docs on it](https://llvm.org/docs/LibFuzzer.html#dictionaries). 
I haven't put that much thought into optimizing the file, so "a", "b", "c", "y" and "x" are all just there bc they are common names for variables in the examples.

**Comment by lenawanel** [comment]
and some lexer tokens are missing, but those can be added later

**Comment by NotAFlyingGoose** [comment]
It looks like there are still some lexer tokens that are missing (no `!`, `!=`, `>=` appears twice), but those could probably be fixed later. Does the fuzzer also add it's own byte mutations on top of the dictionary, or does it only swap out dictionary items for dictionary items?

**Comment by lenawanel** [comment]
@NotAFlyingGoose It also adds it's own byte mutations. 
the dictionary also has to be passed via the `-dict=<file>` flag to the fuzzer.

**Comment by NotAFlyingGoose** [comment]
@lenawanel have you tested it and does it work?

**Comment by lenawanel** [comment]
@NotAFlyingGoose yeah, libfuzzer had a problem with the "\n".

**Comment by NotAFlyingGoose** [comment]
Okay cool

**Pull request merged**
